name: CI

on:
  push:
    branches: [main]
  pull_request:

jobs:
  ci:
    uses: folke/github/.github/workflows/ci.yml@main
    secrets: inherit
    with:
      plugin: markdown-plus
      repo: YousefHadder/markdown-plus.nvim
      docs: false
